# This file is part of kookas/movetobundle.
# 
# (c) Ashleigh Udoh <mail@audoh.co.uk>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kookas.move_to:
        class: Kookas\MoveToBundle\Twig\MoveTo
        arguments: ["@request_stack", "@router"]
        public: false
        tags:
            - { name: twig.extension }